### ISSUE TITLE
optional subtitle 2 makes subtitle 2 subtitle 1

### ISSUE THREAD

**Issue by jeremystocking** [lianalex/my-rails-app#13]
![image](https://user-images.githubusercontent.com/68076394/201560751-b4c15b4a-9783-4ae8-8eee-8da431b82d72.png)
![image](https://user-images.githubusercontent.com/68076394/201560820-378ae799-d777-4b79-b285-32516e99b1f0.png)

When I leave the second optional header blank it makes subtitle2 subtitle1.
- [x] Make it not do that

**Comment by ButlerMW** [comment]
Fixed Bug. Should not create a duplicate
